title: Dan Bartley
email: d.bartley24@imperial.ac.uk
description: >-
  Welcome to my website! Here you can find out about me and my interests.
baseurl: ""
url: ""
github_username: dpb-hydro
theme: minima
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
