title: Dan Bartley
email: d.bartley24@imperial.ac.uk
description: >-
  This is my website! Here you can find out about me and my interests.
baseurl: ""
url: ""
github_username: dpb-hydro
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
